application: go-gae-starter
version: 1
runtime: go
api_version: go1

handlers:
- url: /js
  static_dir: static/js

- url: /css
  static_dir: static/css

- url: /img
  static_dir: static/img

- url: /font
  static_dir: static/font

- url: /*\.ico
  static_dir: static/

- url: /*\.png
  static_dir: static/

- url: /*\.txt
  static_dir: static/

- url: /.*
  script: _go_app